serviceMaps:
  serviceName: request-service
  mappings:
    - version: 1.0
      description: Persists water tanker application detail
      fromTopic: create-water-tanker-booking
      isTransaction: true
      queryMaps:
        - query: INSERT INTO public.upyog_rs_tanker_booking_details(booking_id, booking_no, tenant_id, tanker_type, request_type, no_of_mobile_toilet, additional_details, tanker_quantity, water_quantity, description, applicant_uuid, delivery_date, delivery_time, extra_charge, vendor_id, vehicle_id, driver_id, vehicle_type, vehicle_capacity, booking_createdby, booking_status, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::DATE, ?::TIME, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId
            - jsonPath: $.waterTankerBookingDetail.bookingNo
            - jsonPath: $.waterTankerBookingDetail.tenantId
            - jsonPath: $.waterTankerBookingDetail.tankerType
            - jsonPath: $.waterTankerBookingDetail.requestType
            - jsonPath: $.waterTankerBookingDetail.noOfMobileToilet
            - jsonPath: $.waterTankerBookingDetail.additionalDetails
            - jsonPath: $.waterTankerBookingDetail.tankerQuantity
            - jsonPath: $.waterTankerBookingDetail.waterQuantity
            - jsonPath: $.waterTankerBookingDetail.description
            - jsonPath: $.waterTankerBookingDetail.applicantUuid
            - jsonPath: $.waterTankerBookingDetail.deliveryDate
            - jsonPath: $.waterTankerBookingDetail.deliveryTime
            - jsonPath: $.waterTankerBookingDetail.extraCharge
            - jsonPath: $.waterTankerBookingDetail.vendorId
            - jsonPath: $.waterTankerBookingDetail.vehicleId
            - jsonPath: $.waterTankerBookingDetail.driverId
            - jsonPath: $.waterTankerBookingDetail.vehicleType
            - jsonPath: $.waterTankerBookingDetail.vehicleCapacity
            - jsonPath: $.waterTankerBookingDetail.bookingCreatedBy
            - jsonPath: $.waterTankerBookingDetail.bookingStatus
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdTime
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime

        - query: INSERT INTO public.upyog_rs_applicant_details(applicant_id, booking_id, name, mobile_number, gender, email_id, alternate_number, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail.applicantDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.applicantId
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.bookingId
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.name
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.mobileNumber
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.gender
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.emailId
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.alternateNumber
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdTime
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime

        - query: INSERT INTO public.upyog_rs_address_details(address_id, applicant_id, house_no, address_line_1, address_line_2, street_name, landmark, city, city_code, locality, locality_code, pincode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail.address
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.address.addressId
            - jsonPath: $.waterTankerBookingDetail.address.applicantId
            - jsonPath: $.waterTankerBookingDetail.address.houseNo
            - jsonPath: $.waterTankerBookingDetail.address.addressLine1
            - jsonPath: $.waterTankerBookingDetail.address.addressLine2
            - jsonPath: $.waterTankerBookingDetail.address.streetName
            - jsonPath: $.waterTankerBookingDetail.address.landmark
            - jsonPath: $.waterTankerBookingDetail.address.city
            - jsonPath: $.waterTankerBookingDetail.address.cityCode
            - jsonPath: $.waterTankerBookingDetail.address.locality
            - jsonPath: $.waterTankerBookingDetail.address.localityCode
            - jsonPath: $.waterTankerBookingDetail.address.pincode

        - query: INSERT INTO public.upyog_rs_tanker_booking_details_auditdetails SELECT * FROM public.upyog_rs_tanker_booking_details WHERE booking_id = ?;
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId

    - version: 1.0
      description: Update water tanker application detail
      fromTopic: update-water-tanker-booking
      isTransaction: true
      queryMaps:
        - query: UPDATE public.upyog_rs_tanker_booking_details SET booking_status = ?, vendor_id = ?, vehicle_id = ?, driver_id = ?,  createdby = ?, lastmodifiedby = ?, lastmodifiedtime = ? WHERE booking_id = ?;
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingStatus
            - jsonPath: $.waterTankerBookingDetail.vendorId
            - jsonPath: $.waterTankerBookingDetail.vehicleId
            - jsonPath: $.waterTankerBookingDetail.driverId
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime
            - jsonPath: $.waterTankerBookingDetail.bookingId

        - query: INSERT INTO public.upyog_rs_tanker_booking_details_auditdetails SELECT * FROM public.upyog_rs_tanker_booking_details WHERE booking_id = ?;
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId
