SearchDefinitions:
  moduleName: request-service.water_tanker
  summary: Water Tanker Request Service Inbox API
  version: 1.0.0
  definitions:
    - name: inboxWTSearch
      query:
        baseQuery: Select row_to_json(result) from
          (
          select DISTINCT(urstbd.booking_no),pi.createdtime from 
          upyog_rs_water_tanker_booking_details as urstbd
          INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = urstbd.booking_no
          LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
          $where
          AND pi.createdtime IN (select max(createdtime) from eg_wf_processinstance_v2 wf where wf.businessid = urstbd.booking_no GROUP BY wf.businessid)
          order by pi.createdtime asc $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: urstbd.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: urstbd.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.bookingNo
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset

      output:
        jsonFormat: {"ResponseInfo": {},"waterTankerBookingDetail": []}
        outJsonPath: $.waterTankerBookingDetail
        responseInfoPath: $.ResponseInfo
    - name: inboxWTSearchdesc
      query:
        baseQuery: Select row_to_json(result) from
          (
          select DISTINCT(urstbd.booking_no),pi.createdtime from 
          upyog_rs_water_tanker_booking_details as urstbd
          INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = urstbd.booking_no
          LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
          $where
          AND pi.createdtime IN (select max(createdtime) from eg_wf_processinstance_v2 wf where wf.businessid = urstbd.booking_no GROUP BY wf.businessid)
          order by pi.createdtime desc $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: urstbd.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: urstbd.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.bookingNo
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset

      output:
        jsonFormat: {"ResponseInfo": {},"waterTankerBookingDetail": []}
        outJsonPath: $.waterTankerBookingDetail
        responseInfoPath: $.ResponseInfo
        
    - name: inboxWTSearchCount
      query:
        baseQuery: SELECT row_to_json(TotalCount) from (SELECT COUNT(result) from
          (
          select urstbd.booking_no, pi.createdtime from 
          upyog_rs_water_tanker_booking_details urstbd
          INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = urstbd.booking_no
          LEFT JOIN eg_wf_assignee_v2 assg ON pi.id = assg.processinstanceid
          $where
          AND pi.createdtime IN (select max(createdtime) from eg_wf_processinstance_v2 wf where wf.businessid = urstbd.booking_no GROUP BY wf.businessid)
          order by pi.createdtime asc
          ) result) TotalCount
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: urstbd.tenant_id
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: urstbd.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.bookingNo
          - name: pi.status
            isMandatory: false
            jsonPath: $.searchCriteria.status
          - name: assg.assignee
            isMandatory: false
            jsonPath: $.searchCriteria.assignee
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset

      output:
        jsonFormat: {"ResponseInfo": {},"TotalCount": {}}
        outJsonPath: $.TotalCount
        responseInfoPath: $.ResponseInfo